### PR TITLE
[WIP] Switch to dry-schema

### LINKED ISSUE #222: dry-validation 1.x moves schema support to dry-schema
Updating to dry-validation 1.x (which the gem spec allows) breaks config when `config.schema` is used with:

```
undefined method `Schema' for Dry::Validation:Module (NoMethodError)
```

It appears that the schema support has been moved to a new `dry-schema` gem so I guess some tweaking is needed to support that...

### PR DESCRIPTION
**Pull request by solnic**
This makes `config` work with `dry-schema` which replaced `dry-validation`'s schema DSL. The only caveat is that it works with `ruby >= 2.4`. Oh and of course CI is completely broken but I think there's something with your spec suite because I didn't manage to run specs locally either.

Let me know if this is something you'd like to merge eventually. I'm happy to help.

Fixes #222

### CODE REVIEW

**Comment by solnic** [comment]
@pkuczynski 👋 is this something you'd like to do? `dry-validation 0.x` is basically going away as unsupported and `1.0.0` will be completely different, so if you want to keep settings validation I recommend switching to `dry-schema`, which this PR attempts to do 😄

**Comment by pkuczynski** [comment]
Sure, why not :) I just dont have time to work on anything like this at the moment, but I will happily accept your PR if it works :)

**Comment by mensfeld** [comment]
@pkuczynski @solnic any chance on getting this delivered? It's blocking deps in some of my projects :(

**Comment by solnic** [comment]
Sorry, forgot to mention that we decided to stop using `config` gem so I won't be working on this PR.

**Comment by pkuczynski** [comment]
@solnic out of the interest, what alternative solution did you decided to use?

**Comment by pkuczynski** [comment]
@mensfeld would you like to pick it up from @solnic? I am doing mainly node.js these days, so would not really have time for it I am fraid

**Comment by zbelzer** [comment]
@solnic @mensfeld I'm looking to see this fixed too, at least from a versioning standpoint: https://github.com/railsconfig/config/pull/223

**Comment by solnic** [comment]
> @solnic out of the interest, what alternative solution did you decided to use?

I'll be adding support for YAML configs to `:settings` component in dry-system and we'll switch to that.

**Comment by mensfeld** [comment]
> @mensfeld would you like to pick it up from @solnic? I am doing mainly node.js these days, so would not really have time for it I am afraid

@pkuczynski not really. Dropped this gem as well in favor of native Rails configuration and dry-system config component as well.

**Comment by pkuczynski** [comment]
Fair enough. I am not doing Ruby anymore for the last 5y, so I don't really follow the ecosystem. Closing this PR for now.

**Comment by pkuczynski** [comment]
FYI @solnic and @mensfeld: #224 updated to newest dry-schema and we will release 2.0 version soon, in case you still wanna use it :)
