### ISSUE TITLE
not working with Rails 4.1.0.rc2

### ISSUE THREAD

**Issue by jacquescrocker** [railsconfig/config#70]
having rails_config in the project throws an error on start

```
/Users/jc/.rvm/gems/ruby-2.0.0-p247/bundler/gems/rails_config-a672a110738b/lib/rails_config/integration/rails.rb:8:in `block in <class:Railtie>': undefined method `join' for nil:NilClass (NoMethodError)
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:36:in `call'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:44:in `each'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/application.rb:121:in `initialize'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/railtie.rb:171:in `new'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/railtie.rb:171:in `instance'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/application.rb:90:in `inherited'
  from /Users/jc/Projects/test/config/application.rb:25:in `<module:Contacts>'
  from /Users/jc/Projects/test/config/application.rb:24:in `<top (required)>'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/commands/commands_tasks.rb:146:in `require'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/commands/commands_tasks.rb:146:in `require_application_and_environment!'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /Users/jc/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.0.rc2/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
```
